// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mdf.Repository;

namespace mdf.Migrations
{
    [DbContext(typeof(MDFcontext))]
    [Migration("20191027132017_S1")]
    partial class S1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mdf.Model.LinhaProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("LinhasProducao");
                });

            modelBuilder.Entity("mdf.Model.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LinhaProducaoId");

                    b.Property<Guid?>("TipoMaquinaId");

                    b.HasKey("Id");

                    b.HasIndex("LinhaProducaoId");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("mdf.Model.Operacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("TipoMaquinaId");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("mdf.Model.TipoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("TiposMaquinas");
                });

            modelBuilder.Entity("mdf.Model.Maquina", b =>
                {
                    b.HasOne("mdf.Model.LinhaProducao")
                        .WithMany("ListMaquinas")
                        .HasForeignKey("LinhaProducaoId");

                    b.HasOne("mdf.Model.TipoMaquina", "TipoMaquina")
                        .WithMany()
                        .HasForeignKey("TipoMaquinaId");

                    b.OwnsOne("mdf.Model.ValueObjects.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<Guid>("MaquinaId");

                            b1.Property<string>("Value")
                                .HasColumnName("Localizacao");

                            b1.HasKey("MaquinaId");

                            b1.ToTable("Maquinas");

                            b1.HasOne("mdf.Model.Maquina")
                                .WithOne("Localizacao")
                                .HasForeignKey("mdf.Model.ValueObjects.Localizacao", "MaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("mdf.Model.Operacao", b =>
                {
                    b.HasOne("mdf.Model.TipoMaquina")
                        .WithMany("Operacoes")
                        .HasForeignKey("TipoMaquinaId");

                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("OperacaoId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao")
                                .HasMaxLength(300);

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("mdf.Model.Operacao")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("mdf.Model.ValueObjects.Duracao", "Duracao", b1 =>
                        {
                            b1.Property<Guid>("OperacaoId");

                            b1.Property<long>("Value")
                                .HasColumnName("Duracao");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("mdf.Model.Operacao")
                                .WithOne("Duracao")
                                .HasForeignKey("mdf.Model.ValueObjects.Duracao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
