// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mdf.Repository;

namespace mdf.Migrations
{
    [DbContext(typeof(MDFcontext))]
    [Migration("20191203145934_RemoveExecucaoFerramenta")]
    partial class RemoveExecucaoFerramenta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mdf.Model.Ferramenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Ferramentas");
                });

            modelBuilder.Entity("mdf.Model.JoiningEntities.LinhaProducaoMaquina", b =>
                {
                    b.Property<Guid>("MaquinaId");

                    b.Property<Guid>("LinhaProducaoId");

                    b.HasKey("MaquinaId", "LinhaProducaoId");

                    b.HasIndex("LinhaProducaoId");

                    b.ToTable("LinhaProducaoMaquinas");
                });

            modelBuilder.Entity("mdf.Model.JoiningEntities.TipoMaquinaOperacao", b =>
                {
                    b.Property<Guid>("OperacaoId");

                    b.Property<Guid>("TipoMaquinaId");

                    b.HasKey("OperacaoId", "TipoMaquinaId");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("TipoMaquinaOperacoes");
                });

            modelBuilder.Entity("mdf.Model.LinhaProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("LinhasProducao");
                });

            modelBuilder.Entity("mdf.Model.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("TipoMaquinaId");

                    b.HasKey("Id");

                    b.HasIndex("TipoMaquinaId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("mdf.Model.Operacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("FerramentaId");

                    b.HasKey("Id");

                    b.HasIndex("FerramentaId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("mdf.Model.TipoMaquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("TiposMaquinas");
                });

            modelBuilder.Entity("mdf.Model.Ferramenta", b =>
                {
                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("FerramentaId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao");

                            b1.HasKey("FerramentaId");

                            b1.ToTable("Ferramentas");

                            b1.HasOne("mdf.Model.Ferramenta")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "FerramentaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("mdf.Model.ValueObjects.Duracao", "Setup", b1 =>
                        {
                            b1.Property<Guid>("FerramentaId");

                            b1.Property<long>("Value")
                                .HasColumnName("TempoSetup");

                            b1.HasKey("FerramentaId");

                            b1.ToTable("Ferramentas");

                            b1.HasOne("mdf.Model.Ferramenta")
                                .WithOne("Setup")
                                .HasForeignKey("mdf.Model.ValueObjects.Duracao", "FerramentaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("mdf.Model.JoiningEntities.LinhaProducaoMaquina", b =>
                {
                    b.HasOne("mdf.Model.LinhaProducao", "LinhaProducao")
                        .WithMany("LinhaProducaoMaquinas")
                        .HasForeignKey("LinhaProducaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("mdf.Model.Maquina", "Maquina")
                        .WithMany("LinhaProducaoMaquinas")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("mdf.Model.JoiningEntities.TipoMaquinaOperacao", b =>
                {
                    b.HasOne("mdf.Model.Operacao", "Operacao")
                        .WithMany("TipoMaquinaOperacoes")
                        .HasForeignKey("OperacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("mdf.Model.TipoMaquina")
                        .WithMany("TipoMaquinaOperacoes")
                        .HasForeignKey("TipoMaquinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("mdf.Model.LinhaProducao", b =>
                {
                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("LinhaProducaoId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao");

                            b1.HasKey("LinhaProducaoId");

                            b1.ToTable("LinhasProducao");

                            b1.HasOne("mdf.Model.LinhaProducao")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "LinhaProducaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("mdf.Model.Maquina", b =>
                {
                    b.HasOne("mdf.Model.TipoMaquina", "TipoMaquina")
                        .WithMany()
                        .HasForeignKey("TipoMaquinaId");

                    b.OwnsOne("mdf.Model.ValueObjects.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<Guid>("MaquinaId");

                            b1.Property<string>("Value")
                                .HasColumnName("Localizacao");

                            b1.HasKey("MaquinaId");

                            b1.ToTable("Maquinas");

                            b1.HasOne("mdf.Model.Maquina")
                                .WithOne("Localizacao")
                                .HasForeignKey("mdf.Model.ValueObjects.Localizacao", "MaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("MaquinaId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao");

                            b1.HasKey("MaquinaId");

                            b1.ToTable("Maquinas");

                            b1.HasOne("mdf.Model.Maquina")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "MaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("mdf.Model.Operacao", b =>
                {
                    b.HasOne("mdf.Model.Ferramenta", "Ferramenta")
                        .WithMany()
                        .HasForeignKey("FerramentaId");

                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("OperacaoId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao")
                                .HasMaxLength(300);

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("mdf.Model.Operacao")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("mdf.Model.ValueObjects.Duracao", "Execucao", b1 =>
                        {
                            b1.Property<Guid>("OperacaoId");

                            b1.Property<long>("Value")
                                .HasColumnName("TempoExecucao");

                            b1.HasKey("OperacaoId");

                            b1.ToTable("Operacoes");

                            b1.HasOne("mdf.Model.Operacao")
                                .WithOne("Execucao")
                                .HasForeignKey("mdf.Model.ValueObjects.Duracao", "OperacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("mdf.Model.TipoMaquina", b =>
                {
                    b.OwnsOne("mdf.Model.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("TipoMaquinaId");

                            b1.Property<string>("Value")
                                .HasColumnName("Descricao");

                            b1.HasKey("TipoMaquinaId");

                            b1.ToTable("TiposMaquinas");

                            b1.HasOne("mdf.Model.TipoMaquina")
                                .WithOne("Descricao")
                                .HasForeignKey("mdf.Model.ValueObjects.Descricao", "TipoMaquinaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
