//MDF
export const GET_MAQUINAS = 'GET_MAQUINAS';
export const ADD_MAQUINA = 'ADD_MAQUINA';
export const DELETE_MAQUINA = 'DELETE_MAQUINA';
export const UPDATE_MAQUINA = 'UPDATE_MAQUINA';
export const MAQUINAS_LOADING = 'MAQUINAS_LOADING';

export const LINHAS_PRODUCAO_LOADING = 'LINHAS_PRODUCAO_LOADING';
export const GET_LINHAS_PRODUCAO = 'GET_LINHAS_PRODUCAO';
export const ADD_LINHA_PRODUCAO = 'ADD_LINHA_PRODUCAO';
export const ADD_MAQUINA_LINHA_PRODUCAO = 'ADD_MAQUINA_LINHA_PRODUCAO';
export const UPDATE_LINHA_PRODUCAO = 'UPDATE_LINHA_PRODUCAO';
export const DELETE_LINHA_PRODUCAO = 'DELETE_LINHA_PRODUCAO';

export const OPERACOES_LOADING = "OPERACOES_LOADING";
export const GET_OPERACOES = "GET_OPERACOES";
export const ADD_OPERACAO = "ADD_OPERACAO";
export const DELETE_OPERACAO = "DELETE_OPERACAO";
export const UPDATE_OPERACAO = "UPDATE_OPERACAO";

export const TIPOS_MAQUINA_LOADING = "TIPOS_MAQUINA_LOADING";
export const GET_TIPOS_MAQUINA = "GET_TIPOS_MAQUINA";
export const ADD_TIPO_MAQUINA = "ADD_TIPO_MAQUINA";
export const DELETE_TIPO_MAQUINA = "DELETE_TIPO_MAQUINA";
export const UPDATE_TIPO_MAQUINA = "UPDATE_TIPO_MAQUINA";
export const ADD_OPERACAO_TIPO_MAQUINA = "ADD_OPERACAO_TIPO_MAQUINA";

//MDP
export const PRODUTOS_LOADING = "PRODUTOS_LOADING";
export const GET_PRODUTOS = "GET_PRODUTOS";
export const ADD_PRODUTO = "ADD_PRODUTO";
export const DELETE_PRODUTO = "DELETE_PRODUTO";
export const UPDATE_PRODUTO = "UPDATE_PRODUTO";

export const PLANOS_FABRICO_LOADING = "PLANOS_FABRICO_LOADING";
export const GET_PLANOS_FABRICO = "GET_PLANOS_FABRICO";
export const ADD_PLANO_FABRICO = "ADD_PLANO_FABRICO";
export const DELETE_PLANO_FABRICO = "DELETE_PLANO_FABRICO";
export const UPDATE_PLANO_FABRICO = "UPDATE_PLANO_FABRICO";

//GE
export const ENCOMENDAS_LOADING = "ENCOMENDAS_LOADING";
export const GET_ENCOMENDAS = "GET_ENCOMENDAS";
export const DELETE_ENCOMENDAS = "DELETE_ENCOMENDAS";
export const UPDATE_ENCOMENDA = "UPDATE_ENCOMENDA";
export const ADD_ENCOMENDA = "ADD_ENCOMENDA";


//AUTH
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const MDF_LOGIN = "MDF_LOGIN";
export const MDP_LOGIN = "MDP_LOGIN";

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ERROR = "ERROR";
